### PR TITLE
WIP Check arguments by position

### PR DESCRIPTION
**Pull request by richierocks**
Allows you to pass a numbered argument to `check_arg()`.

### CODE REVIEW

**Comment by richierocks** [comment]
Reverting this to work in progress since it doesn't handle `...` correctly. I think the problem is in the utility function `find_function_calls()`.

**Comment by richierocks** [comment]
I modified `get_args()` so arguments in `...` are now named `..1`, `..2`, `..3` (which is standard R naming). This means you can access them using `check_arg("..1")` etc.

For backwards compatibility `check_arg("...")` is the same as `check_arg("..1")`.

----

There is one failing test for `test_function()`.

https://github.com/datacamp/testwhat/blob/check_arg_by_position/tests/testthat/test-check-function.R#L551

All the tests for `check_function()` and `check_arg()` pass, so we might just be able to get rid of the legacy tests for `test_function()`.

**Comment by richierocks** [comment]
closes https://github.com/datacamp/testwhat/issues/208

**Comment by hermansje** [comment]
Converting `...` to `..1` might relax tests. This PR also destructures the `...` argument, changing positional argument matching.
My commit adds two basic tests for these cases and a solution for the first, that also fixes the test that failed.

The second case could be addressed by not destructuring `...` and only allowing `..n` syntax, which would require the implementation to be reworked.

**Comment by hermansje** [comment]
Before we merge, we should also document the `..n` syntax.

**Pull request merged**
